CREATE TABLE IF NOT EXISTS CATEGORIAS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    CREATE_BY VARCHAR(100),
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS SUB_CATEGORIAS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    CATEGORIA_ID INT,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS(ID)
    );

CREATE TABLE IF NOT EXISTS SERVICIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    PRECIO DECIMAL(10,2),
    CREATE_BY VARCHAR(50),
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AT TIMESTAMP DEFAULT NULL,
    ESTADO VARCHAR(20),
    IMAGEN_URL VARCHAR(255),
    ID_CAT INT,
    ID_SUB_CAT INT,
    FOREIGN KEY (ID_CAT) REFERENCES CATEGORIAS(ID),
    FOREIGN KEY (ID_SUB_CAT) REFERENCES SUB_CATEGORIAS(ID)
    );
